import "./globals.css";
import type { Metadata } from "next";
import {
  Inter,
  Roboto_Mono,
  Manrope,
  Noto_Sans,
  Sofia_Sans,
} from "next/font/google";
import { ThemeProvider } from "@/components/ui/theme-provider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const noto_sans = Noto_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-noto-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const sofia_sans = Sofia_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sofia-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800", "1000"],
});

export const metadata: Metadata = {
  title: "Landing Pages",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${noto_sans.variable}
          ${inter.className}
          ${roboto_mono.variable} 
          ${manrope.variable} 
          ${sofia_sans.variable}
        `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
